name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install 🔧
        uses: CultureHQ/actions-yarn@master
        with:
          cmd: install # will run `yarn install` command
      - name: Build 🔧
        uses: CultureHQ/actions-yarn@master
        with:
          cmd: build-all # will run `yarn build-all` command
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-build # The folder the action should deploy.
